### ISSUE TITLE
Pip requirements.txt file

### ISSUE THREAD

**Issue by leynos** [scotm/canvassing#1]
I think it would be good to have a pip compatible requirements.txt file indicating the minimum required versions of django and whatever else is used.

**Comment by leynos** [comment]
Missed the obvious requirements directory.

**Comment by scotm** [comment]
Hi leynos,

Decided to split it into various requirements files under the requirements directory. local.txt, and production.txt. Will probably subdivide requirements for staging and testing purposes.

Create your virtualenv, change to the project directory then type:

pip install -r requirements/local.txt to set up your development environment.
